FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY client/go.mod client/go.sum ./
RUN go mod download

COPY client/ .

RUN go build -o /raft-client .

FROM alpine:latest
COPY --from=builder /raft-client /raft-client
CMD ["/raft-client"]
